namespace CNutSharp.Library.Models.NutEnums;

[Flags]
public enum SQObjectType
{
    OT_NULL = SQObjTypeField._RT_NULL | SQObjAttrField.SQOBJECT_CANBEFALSE,
    OT_INTEGER = SQObjTypeField._RT_INTEGER | SQObjAttrField.SQOBJECT_NUMERIC | SQObjAttrField.SQOBJECT_CANBEFALSE,
    OT_FLOAT = SQObjTypeField._RT_FLOAT | SQObjAttrField.SQOBJECT_NUMERIC | SQObjAttrField.SQOBJECT_CANBEFALSE,
    OT_BOOL = SQObjTypeField._RT_BOOL | SQObjAttrField.SQOBJECT_CANBEFALSE,
    OT_STRING = SQObjTypeField._RT_STRING | SQObjAttrField.SQOBJECT_REF_COUNTED,
    OT_TABLE = SQObjTypeField._RT_TABLE | SQObjAttrField.SQOBJECT_REF_COUNTED | SQObjAttrField.SQOBJECT_DELEGABLE,
    OT_ARRAY = SQObjTypeField._RT_ARRAY | SQObjAttrField.SQOBJECT_REF_COUNTED,
    OT_USERDATA = SQObjTypeField._RT_USERDATA | SQObjAttrField.SQOBJECT_REF_COUNTED | SQObjAttrField.SQOBJECT_DELEGABLE,
    OT_CLOSURE = SQObjTypeField._RT_CLOSURE | SQObjAttrField.SQOBJECT_REF_COUNTED,
    OT_NATIVECLOSURE = SQObjTypeField._RT_NATIVECLOSURE | SQObjAttrField.SQOBJECT_REF_COUNTED,
    OT_GENERATOR = SQObjTypeField._RT_GENERATOR | SQObjAttrField.SQOBJECT_REF_COUNTED,
    OT_USERPOINTER = SQObjTypeField._RT_USERPOINTER,
    OT_THREAD = SQObjTypeField._RT_THREAD | SQObjAttrField.SQOBJECT_REF_COUNTED,
    OT_FUNCPROTO = SQObjTypeField._RT_FUNCPROTO | SQObjAttrField.SQOBJECT_REF_COUNTED,  // internal usage only
    OT_CLASS = SQObjTypeField._RT_CLASS | SQObjAttrField.SQOBJECT_REF_COUNTED,
    OT_INSTANCE = SQObjTypeField._RT_INSTANCE | SQObjAttrField.SQOBJECT_REF_COUNTED | SQObjAttrField.SQOBJECT_DELEGABLE,
    OT_WEAKREF = SQObjTypeField._RT_WEAKREF | SQObjAttrField.SQOBJECT_REF_COUNTED,
    OT_OUTER = SQObjTypeField._RT_OUTER | SQObjAttrField.SQOBJECT_REF_COUNTED      // internal usage only
}